 * Serving Flask app "api" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: on
Traceback (most recent call last):
  File "api.py", line 11, in <module>
    app.run(host='0.0.0.0',port=80)
  File "/usr/local/lib64/python3.7/site-packages/flask/app.py", line 944, in run
    run_simple(host, port, self, **options)
  File "/usr/local/lib/python3.7/site-packages/werkzeug/serving.py", line 987, in run_simple
    s.bind(server_address)
OSError: [Errno 98] Address already in use
 * Serving Flask app "api" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: on
 * Running on http://0.0.0.0:80/ (Press CTRL+C to quit)
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 229-602-278
96.27.76.180 - - [01/Jun/2019 13:33:38] "GET / HTTP/1.1" 200 -
96.27.76.180 - - [01/Jun/2019 13:33:48] "GET / HTTP/1.1" 200 -
96.27.76.180 - - [01/Jun/2019 13:33:59] "GET / HTTP/1.1" 200 -
96.27.76.180 - - [01/Jun/2019 13:33:59] "GET /favicon.ico HTTP/1.1" 404 -
96.27.76.180 - - [01/Jun/2019 13:34:06] "GET / HTTP/1.1" 200 -
96.27.76.180 - - [01/Jun/2019 13:34:06] "GET /favicon.ico HTTP/1.1" 404 -
96.27.76.180 - - [01/Jun/2019 13:34:07] "GET / HTTP/1.1" 200 -
96.27.76.180 - - [01/Jun/2019 13:34:07] "GET /favicon.ico HTTP/1.1" 404 -
96.27.76.180 - - [01/Jun/2019 13:34:07] "GET / HTTP/1.1" 200 -
96.27.76.180 - - [01/Jun/2019 13:34:08] "GET /favicon.ico HTTP/1.1" 404 -
